# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [14]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [16]:
A = np.arange(1, 16).reshape(3,5)
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [21]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [23]:
Elementwise_subtraction = B - C
Elementwise_multiplication = B * C
Matrix_multiplication = B @ C

print(Elementwise_subtraction)
print(Elementwise_multiplication)
print(Matrix_multiplication)


[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [26]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# Calculate the minimum value in the whole matrix.
Exponentiate = np.exp(B)
print(Exponentiate)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [30]:
# Calculate the minimum value in the whole matrix.
min_value_matrix = np.min(B)
print(min_value_matrix)

1


In [32]:
# Calculcate the minimum value in each row.
min_value_each_row = np.min(B, axis = 1)
print(min_value_each_row)
# Calculcate the minimum value in each column.
min_value_each_column = np.min(B, axis = 0)
print(min_value_each_column)

[1 4 7]
[1 2 3]


In [34]:
# Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
min_value_index = np.argmin(B)
min_value_index_matrix = np.unravel_index(min_value_index, B.shape)
print(min_value_index)
print(min_value_index_matrix)

0
(0, 0)


In [36]:
# Find the index value for the minimum value in each row (hint: use np.argmin).
min_value_index_each_row = np.argmin(B, axis = 1)
print(min_value_index_each_row)
# Calculate the sum for all elements.
sum_element = np.sum(B)
sum = B.sum()
print(sum_element, sum)
# Calculate the mean for each column.
mean_each_column = np.mean(B, axis = 0)
print(mean_each_column)
# Calculate the median for each column.
median_each_colum = np.median(B, axis = 0)
print(median_each_colum)

[0 0 0]
45 45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [39]:
# A is a 2-dimentional (3*3) NumPy array
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
# Select a specific row along the specified axis, i.e. "row slicing"
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [12]:
# A är en 3*5 matrix vilket finns två axes: rad med axis 0 och column med axis 1. 
# A[1] menar att slicea andra raden av A, villken är (6,7,8,9,10)
# Select a specific colomn along the specified axis, i.e. "column slicing"

Column = [i[1] for i in A]
print(Column)

[2, 7, 12]


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [41]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [43]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [45]:
for row in A:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [47]:
for element in A.flatten():
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [21]:
# Skapa en 1-dimentional NumPy array, vilken innerhåller talet from 0 to 29

a = np.arange(30)

# Reshapes the above array "a" into a 3-dimentional array "b", which is specified as (2,3,-1)
# "-1" is used as a placeholer 占位符, 
# -1 is calculated to be 5, ensuring that the reshaped array b has the same number of elements as the original array a.
b = a.reshape((2, 3, -1))

print(a)
print()

print(b)

print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
3


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [51]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[1, 1],[1, 1]])

if m2.shape != m1.shape:
    raise ValueError("Arrays m1 and m2 must be the same shape for addition.")

# The smaller array (m2) to be broadcasted to match the shape of the larger array (m1) so that element-wise addition can take place.
print(m1 + m2)

[[2 3]
 [4 5]]


In [49]:
# Test med fel array
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])

# The smaller array (m2) to be broadcasted to match the shape of the larger array (m1) so that element-wise addition can take place.
print(m1 + m2)

if m2.shape != m1.shape:
    raise ValueError("Arrays m1 and m2 must be the same shape for addition.")

result = m1 + m2
print(result)

[[2 3]
 [4 5]]


ValueError: Arrays m1 and m2 must be the same shape for addition.

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [51]:
# Chapter 2, exercise 1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


In [62]:
print(B - 2*A)
print()
print(3*C - E)
print()

# print(A@C)
print()
print(C@D)
print()
print(C@B)

[[ 0 -4  3]
 [ 0 -2 -4]]

[[2 5]
 [4 1]]


[[11 10]
 [10 11]]

[[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [53]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Check if both imputs are numpy.ndarrays
    if not (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)):
        raise ValueError("Both inputs should be numpy.ndarrays!")
        
    # Perform addition if specified
    if operation == "add":
        if matrix1.shape != matrix2.shape:
            raise ValueError("Both Matrixs must have the same size!")
        result = matrix1 + matrix2
    
    # Perform multiplication if specified
    elif operation == "multiply":
        # Check if the sizes conform for multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix!")
            # numpy.dot and numpy.matmul for matrix multiplication that explicitly enforce shape compatibility.
        result = np.dot(matrix1, matrix2)
    else:
        raise ValueError("Invalid operation. Use 'add' or 'multiply'")
    
    return result

# Example usage:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])


# Add the matrices
result_addition = add_mult_matrices(matrix1, matrix2, "add")
print(result_addition)

# Multiply the matrices
result_multiplication = add_mult_matrices(matrix1, matrix2, "multiply")
print(result_multiplication)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


**Chap2. Question 2**

In [23]:
# Chapter 2, exercise 2
import numpy as np

A = np.array([[1,2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])

AB = np.dot(A,B)
AC = np.dot(A,C)

if np.array_equal(AB, AC):
    print("AB is equal to AC.")
else:
    print("AB is not equal to AC.")
    
if np.all(B == C):
    print("B is equal to C.")
else:
    print("B is not equal to C.")
    





AB is equal to AC.
B is not equal to C.


**Chap2. Question 3**

In [25]:
# Chapter 2, exercise 3
import numpy as np

A = np.array([[1,1,1],[1,2,3],[1,3,4]])
D = np.array([[2,0,0],[0,3,0],[0,0,4]])

AD = np.dot(A, D)
DA = np.dot(D, A)
print(AD)
print()
print(DA)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [90]:
import numpy as np

A = np.array([[1, -1],[-1,1]])
B = np.array([[-1,1],[1,-1]])

AB = np.dot(A, B)
print(AB)

[[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [103]:
import numpy as np

A = np.array([[5,6],[4,5]])
B = np.array([[6,4],[3,3]])

# "np.linalg.inv" is used to calculated the inverses of matrix
A_inv = np.linalg.inv(A)
print(A_inv)
print()

# 矩阵对象可以通过.I 更方便的求逆矩阵
a = np.matrix(A)
print(a.I)
print()
try:
    B_inv = np.linalg.inv(B)
    print(B_inv)
except np.linalg.LinAlgError:
    print("Inverse of B does not exist.")

[[ 5. -6.]
 [-4.  5.]]

[[ 5. -6.]
 [-4.  5.]]

[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [105]:
import numpy as np

A = np.array([[2,2],[1,2]])

A_inv = np.linalg.inv(A)
print(A_inv)
print()
a = np.matrix(A)
print(a.I)

[[ 1.  -1. ]
 [-0.5  1. ]]

[[ 1.  -1. ]
 [-0.5  1. ]]


**Chap10. Question 1 a)**

In [108]:
import numpy as np

# Define the coefficient matrix A and the right-hand side vector B
A = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])
B = np.array([-7,5,2])

# Solve for the variables x1, x2, x3
# The method "np.linalg.solve" is used to solve system of linear equation of Ax = B
x = np.linalg.solve(A, B)

print("Solution:")
print("x1 = ", x[0])
print("x2 = ", x[1])
print("x3 = ", x[2])

Solution:
x1 =  2.999999999999998
x2 =  3.9999999999999964
x3 =  -5.999999999999991


**Chap10. Question 1 b)**

In [110]:
import numpy as np

A = np.array([[1,-2,3],[-1,3,-1],[2,-5,5]])
B = np.array([1,-1,1])

x = np.linalg.solve(A,B)

print("Solution:")
print("x1 = ", x[0])
print("x2 = ", x[1])
print("x3 = ", x[2])

Solution:
x1 =  8.0
x2 =  2.0
x3 =  -1.0


**Chap 12. Question 1**

In [111]:
import numpy as np

matrix = np.array([[3,-7,-2],[-3,5,1],[6,-4,0]])

try:
    matrix_inv = np.linalg.inv(matrix)
    print( matrix_inv)
except np.linalg.LinAlgError:
    print("The matrix is singular and does not have an inverse.")

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [116]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

# "True" indicates that both arrays share the same underlying data. v2 is view of v1
print("Is v2 a view of v1?", v2.base is v1)

v2[-1] = 123
# Because they are views of the same data
print(v1)

[0 1 2 3]
[2 3]
Is v2 a view of v1? True
[  0   1   2 123]


In [117]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [118]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
